package com.tactile.tact.database.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.tactile.tact.database.entities.ContactFI;
import com.tactile.tact.database.entities.FrozenFeedItem;

import com.tactile.tact.database.entities.ContactFeedItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CONTACT_FEED_ITEM.
*/
public class ContactFeedItemDao extends AbstractDao<ContactFeedItem, Long> {

    public static final String TABLENAME = "CONTACT_FEED_ITEM";

    /**
     * Properties of entity ContactFeedItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ContactId = new Property(1, long.class, "contactId", false, "CONTACT_ID");
        public final static Property FeedItemId = new Property(2, long.class, "feedItemId", false, "FEED_ITEM_ID");
    };

    private DaoSession daoSession;

    private Query<ContactFeedItem> contactFI_ContactFeedItemsQuery;
    private Query<ContactFeedItem> frozenFeedItem_ContactFeedItemsQuery;

    public ContactFeedItemDao(DaoConfig config) {
        super(config);
    }
    
    public ContactFeedItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CONTACT_FEED_ITEM' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CONTACT_ID' INTEGER NOT NULL ," + // 1: contactId
                "'FEED_ITEM_ID' INTEGER NOT NULL );"); // 2: feedItemId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CONTACT_FEED_ITEM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ContactFeedItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getContactId());
        stmt.bindLong(3, entity.getFeedItemId());
    }

    @Override
    protected void attachEntity(ContactFeedItem entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ContactFeedItem readEntity(Cursor cursor, int offset) {
        ContactFeedItem entity = new ContactFeedItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // contactId
            cursor.getLong(offset + 2) // feedItemId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ContactFeedItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContactId(cursor.getLong(offset + 1));
        entity.setFeedItemId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ContactFeedItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ContactFeedItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "contactFeedItems" to-many relationship of ContactFI. */
    public List<ContactFeedItem> _queryContactFI_ContactFeedItems(long contactId) {
        synchronized (this) {
            if (contactFI_ContactFeedItemsQuery == null) {
                QueryBuilder<ContactFeedItem> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ContactId.eq(null));
                contactFI_ContactFeedItemsQuery = queryBuilder.build();
            }
        }
        Query<ContactFeedItem> query = contactFI_ContactFeedItemsQuery.forCurrentThread();
        query.setParameter(0, contactId);
        return query.list();
    }

    /** Internal query to resolve the "contactFeedItems" to-many relationship of FrozenFeedItem. */
    public List<ContactFeedItem> _queryFrozenFeedItem_ContactFeedItems(long feedItemId) {
        synchronized (this) {
            if (frozenFeedItem_ContactFeedItemsQuery == null) {
                QueryBuilder<ContactFeedItem> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FeedItemId.eq(null));
                frozenFeedItem_ContactFeedItemsQuery = queryBuilder.build();
            }
        }
        Query<ContactFeedItem> query = frozenFeedItem_ContactFeedItemsQuery.forCurrentThread();
        query.setParameter(0, feedItemId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getContactFIDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getFrozenFeedItemDao().getAllColumns());
            builder.append(" FROM CONTACT_FEED_ITEM T");
            builder.append(" LEFT JOIN CONTACT_FI T0 ON T.'CONTACT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN FROZEN_FEED_ITEM T1 ON T.'FEED_ITEM_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ContactFeedItem loadCurrentDeep(Cursor cursor, boolean lock) {
        ContactFeedItem entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ContactFI contact = loadCurrentOther(daoSession.getContactFIDao(), cursor, offset);
         if(contact != null) {
            entity.setContact(contact);
        }
        offset += daoSession.getContactFIDao().getAllColumns().length;

        FrozenFeedItem feedItem = loadCurrentOther(daoSession.getFrozenFeedItemDao(), cursor, offset);
         if(feedItem != null) {
            entity.setFeedItem(feedItem);
        }

        return entity;    
    }

    public ContactFeedItem loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ContactFeedItem> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ContactFeedItem> list = new ArrayList<ContactFeedItem>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ContactFeedItem> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ContactFeedItem> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
