package com.tactile.tact.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.tactile.tact.database.entities.GlobalSyncStatus;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GLOBAL_SYNC_STATUS.
*/
public class GlobalSyncStatusDao extends AbstractDao<GlobalSyncStatus, Long> {

    public static final String TABLENAME = "GLOBAL_SYNC_STATUS";

    /**
     * Properties of entity GlobalSyncStatus.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Version = new Property(1, Integer.class, "version", false, "VERSION");
        public final static Property LowerBound = new Property(2, Long.class, "lowerBound", false, "LOWER_BOUND");
        public final static Property UpperBound = new Property(3, Long.class, "upperBound", false, "UPPER_BOUND");
        public final static Property Timestamp = new Property(4, Long.class, "timestamp", false, "TIMESTAMP");
    };


    public GlobalSyncStatusDao(DaoConfig config) {
        super(config);
    }
    
    public GlobalSyncStatusDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GLOBAL_SYNC_STATUS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'VERSION' INTEGER," + // 1: version
                "'LOWER_BOUND' INTEGER," + // 2: lowerBound
                "'UPPER_BOUND' INTEGER," + // 3: upperBound
                "'TIMESTAMP' INTEGER);"); // 4: timestamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GLOBAL_SYNC_STATUS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GlobalSyncStatus entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(2, version);
        }
 
        Long lowerBound = entity.getLowerBound();
        if (lowerBound != null) {
            stmt.bindLong(3, lowerBound);
        }
 
        Long upperBound = entity.getUpperBound();
        if (upperBound != null) {
            stmt.bindLong(4, upperBound);
        }
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(5, timestamp);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GlobalSyncStatus readEntity(Cursor cursor, int offset) {
        GlobalSyncStatus entity = new GlobalSyncStatus( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // version
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // lowerBound
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // upperBound
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // timestamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GlobalSyncStatus entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVersion(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setLowerBound(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setUpperBound(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setTimestamp(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GlobalSyncStatus entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GlobalSyncStatus entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
