package com.tactile.tact.database.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GLOBAL_SYNC_STATUS.
 */
public class GlobalSyncStatus {

    private Long id;
    private Integer version;
    private Long lowerBound;
    private Long upperBound;
    private Long timestamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GlobalSyncStatus() {
    }

    public GlobalSyncStatus(Long id) {
        this.id = id;
    }

    public GlobalSyncStatus(Long id, Integer version, Long lowerBound, Long upperBound, Long timestamp) {
        this.id = id;
        this.version = version;
        this.lowerBound = lowerBound;
        this.upperBound = upperBound;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Long getLowerBound() {
        return lowerBound;
    }

    public void setLowerBound(Long lowerBound) {
        this.lowerBound = lowerBound;
    }

    public Long getUpperBound() {
        return upperBound;
    }

    public void setUpperBound(Long upperBound) {
        this.upperBound = upperBound;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
