package com.tactile.tact.database.entities;

import java.util.List;
import com.tactile.tact.database.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.tactile.tact.database.dao.FrozenFeedItemDao;
import com.tactile.tact.database.dao.OpportunityFIDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table OPPORTUNITY_FI.
 */
public class OpportunityFI {

    private Long id;
    private String opportunityId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient OpportunityFIDao myDao;

    private List<FrozenFeedItem> feedItems;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OpportunityFI() {
    }

    public OpportunityFI(Long id) {
        this.id = id;
    }

    public OpportunityFI(Long id, String opportunityId) {
        this.id = id;
        this.opportunityId = opportunityId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getOpportunityFIDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOpportunityId() {
        return opportunityId;
    }

    public void setOpportunityId(String opportunityId) {
        this.opportunityId = opportunityId;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<FrozenFeedItem> getFeedItems() {
        if (feedItems == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            FrozenFeedItemDao targetDao = daoSession.getFrozenFeedItemDao();
            List<FrozenFeedItem> feedItemsNew = targetDao._queryOpportunityFI_FeedItems(id);
            synchronized (this) {
                if(feedItems == null) {
                    feedItems = feedItemsNew;
                }
            }
        }
        return feedItems;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetFeedItems() {
        feedItems = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
